### ISSUE TITLE
When should the MacGap website be ready?

### ISSUE THREAD

**Issue by jeff-h** [MacGapProject/MacGapProject.github.io#2]
> Not before MacGap2 is ready?

I actually think it should go up asap; we can modify the wording slightly to say version 2 is in alpha or beta.

This will also give me a chance to sort out the CNAME stuff for the macgap.com domain.

**Comment by PercevalSA** [comment]
http://macgap.com redirects to a phishing website.

**Comment by jeff-h** [comment]
Unfortunately it can't be helped. I was paying personally for the domain for a number of years and decided to discontinue doing so; it seems some annoying person has decided to purchase it for their own nefarious purposes.
